### ISSUE TITLE
About Pre-train Model

### ISSUE THREAD

**Issue by Ning850517** [bepierre/SpeechVGG#2]
Hello,
I already downloaded the Pre-train models,
I want to ask how can I test the Pre-train model(.h5 file) with data,
thank you.

**Comment by bepierre** [comment]
We are planing to push a commit soon with some examples of how to use the model.

**Comment by Ning850517** [comment]
Thank you very much.
I'll look forward to it. :))

**Comment by bepierre** [comment]
We updated the repo ! Closing for now
